MISSING_INPUT_TITLE = 'Missing Input!'
SUCCESS_TITLE = 'Success!'
MAX_EVENT_TITLE = 'Max Event Reached!'

EVENT_DETAILS_PANEL_ROWS = 12
EVENT_DETAILS_PANEL_ROW_GAP = 10
EVENT_DETAILS_PANEL_DETAIL_GAP = 10

MAIN_WINDOW_ASPECT = 0.85
