MISSING_INPUT_TITLE = 'Missing Input!'
SUCCESS_TITLE = 'Success!'
MAX_EVENT_TITLE = 'Max Event Reached!'

# Main Window
MAIN_WINDOW_ASPECT = 0.85

# Main Page
TEXT_BOX_MODIFIER = 0.5

# App Toolbar
APP_TOOLBAR_GAP_X = 20
APP_TOOLBAR_GAP_Y = 10

# Events Detail/ Events Card
EVENT_ROW_GAP = 10

# Event Detail Panel
EVENT_DETAILS_PANEL_ROWS = 12
EVENT_DETAILS_PANEL_DETAIL_GAP = 10
EVENT_DETAILS_PANEL_ENTRY_WIDTH_MODIFIER = 0.7

# Event Detail Card
EVENT_DETAILS_PANEL_CARD_GAP = 5
EVENT_DETAILS_CARD_ENTRY_WIDTH_MODIFIER = 0.6